AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for creating EC2 instance and Security Group
          
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c4c4bd6cf0c5fe52
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name 
          Value: MyEC2Instance
        - Key: CustomTag 
          Value: TeachMeSkills
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y git
    
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instance
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 12345
          ToPort: 12345