version: "3"
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example

  web:
    image: php:apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  phpmyadmin: 
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example