---
- name: installation of apache / downloading html page
  hosts: debian_family
  become: yes

  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: installing apache web server
    yum: name=apache2 state=latest

  - name: copying html-file to servers
    copy: src={{ source_file }}  dest={{ destin_file }} mode=775
    notify: restart apache after changes

  - name: launch and enable on startup
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restart apache after changes
    service: name=apache2 state=restarted


- name: installation of apache / downloading html page
  hosts: centos_hosts
  become: yes

  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: installing apache web server
    yum: name=httpd state=latest

  - name: copying html-file to servers
    copy: src={{ source_file }}  dest={{ destin_file }} mode=775
    notify: restart apache after changes

  - name: launch and enable on startup
    service: name=httpd state=started enabled=yes

  handlers:
  - name: restart apache after changes
    service: name=httpd state=restarted


